# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lengyu/CLionProjects/SimpleHTTPServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lengyu/CLionProjects/SimpleHTTPServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lengyu/CLionProjects/SimpleHTTPServer/CMakeFiles /home/lengyu/CLionProjects/SimpleHTTPServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lengyu/CLionProjects/SimpleHTTPServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named httpServer

# Build rule for target.
httpServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httpServer
.PHONY : httpServer

# fast build rule for target.
httpServer/fast:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/build
.PHONY : httpServer/fast

SimpleHTTPServer/base/CurrentThread.o: SimpleHTTPServer/base/CurrentThread.cpp.o

.PHONY : SimpleHTTPServer/base/CurrentThread.o

# target to build an object file
SimpleHTTPServer/base/CurrentThread.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/CurrentThread.cpp.o
.PHONY : SimpleHTTPServer/base/CurrentThread.cpp.o

SimpleHTTPServer/base/CurrentThread.i: SimpleHTTPServer/base/CurrentThread.cpp.i

.PHONY : SimpleHTTPServer/base/CurrentThread.i

# target to preprocess a source file
SimpleHTTPServer/base/CurrentThread.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/CurrentThread.cpp.i
.PHONY : SimpleHTTPServer/base/CurrentThread.cpp.i

SimpleHTTPServer/base/CurrentThread.s: SimpleHTTPServer/base/CurrentThread.cpp.s

.PHONY : SimpleHTTPServer/base/CurrentThread.s

# target to generate assembly for a file
SimpleHTTPServer/base/CurrentThread.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/CurrentThread.cpp.s
.PHONY : SimpleHTTPServer/base/CurrentThread.cpp.s

SimpleHTTPServer/base/GlobalConfig.o: SimpleHTTPServer/base/GlobalConfig.cpp.o

.PHONY : SimpleHTTPServer/base/GlobalConfig.o

# target to build an object file
SimpleHTTPServer/base/GlobalConfig.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/GlobalConfig.cpp.o
.PHONY : SimpleHTTPServer/base/GlobalConfig.cpp.o

SimpleHTTPServer/base/GlobalConfig.i: SimpleHTTPServer/base/GlobalConfig.cpp.i

.PHONY : SimpleHTTPServer/base/GlobalConfig.i

# target to preprocess a source file
SimpleHTTPServer/base/GlobalConfig.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/GlobalConfig.cpp.i
.PHONY : SimpleHTTPServer/base/GlobalConfig.cpp.i

SimpleHTTPServer/base/GlobalConfig.s: SimpleHTTPServer/base/GlobalConfig.cpp.s

.PHONY : SimpleHTTPServer/base/GlobalConfig.s

# target to generate assembly for a file
SimpleHTTPServer/base/GlobalConfig.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/GlobalConfig.cpp.s
.PHONY : SimpleHTTPServer/base/GlobalConfig.cpp.s

SimpleHTTPServer/base/HTTPTask.o: SimpleHTTPServer/base/HTTPTask.cpp.o

.PHONY : SimpleHTTPServer/base/HTTPTask.o

# target to build an object file
SimpleHTTPServer/base/HTTPTask.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/HTTPTask.cpp.o
.PHONY : SimpleHTTPServer/base/HTTPTask.cpp.o

SimpleHTTPServer/base/HTTPTask.i: SimpleHTTPServer/base/HTTPTask.cpp.i

.PHONY : SimpleHTTPServer/base/HTTPTask.i

# target to preprocess a source file
SimpleHTTPServer/base/HTTPTask.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/HTTPTask.cpp.i
.PHONY : SimpleHTTPServer/base/HTTPTask.cpp.i

SimpleHTTPServer/base/HTTPTask.s: SimpleHTTPServer/base/HTTPTask.cpp.s

.PHONY : SimpleHTTPServer/base/HTTPTask.s

# target to generate assembly for a file
SimpleHTTPServer/base/HTTPTask.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/HTTPTask.cpp.s
.PHONY : SimpleHTTPServer/base/HTTPTask.cpp.s

SimpleHTTPServer/base/ListenServer.o: SimpleHTTPServer/base/ListenServer.cpp.o

.PHONY : SimpleHTTPServer/base/ListenServer.o

# target to build an object file
SimpleHTTPServer/base/ListenServer.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/ListenServer.cpp.o
.PHONY : SimpleHTTPServer/base/ListenServer.cpp.o

SimpleHTTPServer/base/ListenServer.i: SimpleHTTPServer/base/ListenServer.cpp.i

.PHONY : SimpleHTTPServer/base/ListenServer.i

# target to preprocess a source file
SimpleHTTPServer/base/ListenServer.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/ListenServer.cpp.i
.PHONY : SimpleHTTPServer/base/ListenServer.cpp.i

SimpleHTTPServer/base/ListenServer.s: SimpleHTTPServer/base/ListenServer.cpp.s

.PHONY : SimpleHTTPServer/base/ListenServer.s

# target to generate assembly for a file
SimpleHTTPServer/base/ListenServer.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/ListenServer.cpp.s
.PHONY : SimpleHTTPServer/base/ListenServer.cpp.s

SimpleHTTPServer/base/main.o: SimpleHTTPServer/base/main.cpp.o

.PHONY : SimpleHTTPServer/base/main.o

# target to build an object file
SimpleHTTPServer/base/main.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/main.cpp.o
.PHONY : SimpleHTTPServer/base/main.cpp.o

SimpleHTTPServer/base/main.i: SimpleHTTPServer/base/main.cpp.i

.PHONY : SimpleHTTPServer/base/main.i

# target to preprocess a source file
SimpleHTTPServer/base/main.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/main.cpp.i
.PHONY : SimpleHTTPServer/base/main.cpp.i

SimpleHTTPServer/base/main.s: SimpleHTTPServer/base/main.cpp.s

.PHONY : SimpleHTTPServer/base/main.s

# target to generate assembly for a file
SimpleHTTPServer/base/main.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/base/main.cpp.s
.PHONY : SimpleHTTPServer/base/main.cpp.s

SimpleHTTPServer/tool/Buffer.o: SimpleHTTPServer/tool/Buffer.cpp.o

.PHONY : SimpleHTTPServer/tool/Buffer.o

# target to build an object file
SimpleHTTPServer/tool/Buffer.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Buffer.cpp.o
.PHONY : SimpleHTTPServer/tool/Buffer.cpp.o

SimpleHTTPServer/tool/Buffer.i: SimpleHTTPServer/tool/Buffer.cpp.i

.PHONY : SimpleHTTPServer/tool/Buffer.i

# target to preprocess a source file
SimpleHTTPServer/tool/Buffer.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Buffer.cpp.i
.PHONY : SimpleHTTPServer/tool/Buffer.cpp.i

SimpleHTTPServer/tool/Buffer.s: SimpleHTTPServer/tool/Buffer.cpp.s

.PHONY : SimpleHTTPServer/tool/Buffer.s

# target to generate assembly for a file
SimpleHTTPServer/tool/Buffer.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Buffer.cpp.s
.PHONY : SimpleHTTPServer/tool/Buffer.cpp.s

SimpleHTTPServer/tool/Cache.o: SimpleHTTPServer/tool/Cache.cpp.o

.PHONY : SimpleHTTPServer/tool/Cache.o

# target to build an object file
SimpleHTTPServer/tool/Cache.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Cache.cpp.o
.PHONY : SimpleHTTPServer/tool/Cache.cpp.o

SimpleHTTPServer/tool/Cache.i: SimpleHTTPServer/tool/Cache.cpp.i

.PHONY : SimpleHTTPServer/tool/Cache.i

# target to preprocess a source file
SimpleHTTPServer/tool/Cache.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Cache.cpp.i
.PHONY : SimpleHTTPServer/tool/Cache.cpp.i

SimpleHTTPServer/tool/Cache.s: SimpleHTTPServer/tool/Cache.cpp.s

.PHONY : SimpleHTTPServer/tool/Cache.s

# target to generate assembly for a file
SimpleHTTPServer/tool/Cache.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Cache.cpp.s
.PHONY : SimpleHTTPServer/tool/Cache.cpp.s

SimpleHTTPServer/tool/HTTP/httpContext.o: SimpleHTTPServer/tool/HTTP/httpContext.cpp.o

.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.o

# target to build an object file
SimpleHTTPServer/tool/HTTP/httpContext.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/HTTP/httpContext.cpp.o
.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.cpp.o

SimpleHTTPServer/tool/HTTP/httpContext.i: SimpleHTTPServer/tool/HTTP/httpContext.cpp.i

.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.i

# target to preprocess a source file
SimpleHTTPServer/tool/HTTP/httpContext.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/HTTP/httpContext.cpp.i
.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.cpp.i

SimpleHTTPServer/tool/HTTP/httpContext.s: SimpleHTTPServer/tool/HTTP/httpContext.cpp.s

.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.s

# target to generate assembly for a file
SimpleHTTPServer/tool/HTTP/httpContext.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/HTTP/httpContext.cpp.s
.PHONY : SimpleHTTPServer/tool/HTTP/httpContext.cpp.s

SimpleHTTPServer/tool/LogStream.o: SimpleHTTPServer/tool/LogStream.cpp.o

.PHONY : SimpleHTTPServer/tool/LogStream.o

# target to build an object file
SimpleHTTPServer/tool/LogStream.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/LogStream.cpp.o
.PHONY : SimpleHTTPServer/tool/LogStream.cpp.o

SimpleHTTPServer/tool/LogStream.i: SimpleHTTPServer/tool/LogStream.cpp.i

.PHONY : SimpleHTTPServer/tool/LogStream.i

# target to preprocess a source file
SimpleHTTPServer/tool/LogStream.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/LogStream.cpp.i
.PHONY : SimpleHTTPServer/tool/LogStream.cpp.i

SimpleHTTPServer/tool/LogStream.s: SimpleHTTPServer/tool/LogStream.cpp.s

.PHONY : SimpleHTTPServer/tool/LogStream.s

# target to generate assembly for a file
SimpleHTTPServer/tool/LogStream.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/LogStream.cpp.s
.PHONY : SimpleHTTPServer/tool/LogStream.cpp.s

SimpleHTTPServer/tool/Logger.o: SimpleHTTPServer/tool/Logger.cpp.o

.PHONY : SimpleHTTPServer/tool/Logger.o

# target to build an object file
SimpleHTTPServer/tool/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logger.cpp.o
.PHONY : SimpleHTTPServer/tool/Logger.cpp.o

SimpleHTTPServer/tool/Logger.i: SimpleHTTPServer/tool/Logger.cpp.i

.PHONY : SimpleHTTPServer/tool/Logger.i

# target to preprocess a source file
SimpleHTTPServer/tool/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logger.cpp.i
.PHONY : SimpleHTTPServer/tool/Logger.cpp.i

SimpleHTTPServer/tool/Logger.s: SimpleHTTPServer/tool/Logger.cpp.s

.PHONY : SimpleHTTPServer/tool/Logger.s

# target to generate assembly for a file
SimpleHTTPServer/tool/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logger.cpp.s
.PHONY : SimpleHTTPServer/tool/Logger.cpp.s

SimpleHTTPServer/tool/Logging.o: SimpleHTTPServer/tool/Logging.cpp.o

.PHONY : SimpleHTTPServer/tool/Logging.o

# target to build an object file
SimpleHTTPServer/tool/Logging.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logging.cpp.o
.PHONY : SimpleHTTPServer/tool/Logging.cpp.o

SimpleHTTPServer/tool/Logging.i: SimpleHTTPServer/tool/Logging.cpp.i

.PHONY : SimpleHTTPServer/tool/Logging.i

# target to preprocess a source file
SimpleHTTPServer/tool/Logging.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logging.cpp.i
.PHONY : SimpleHTTPServer/tool/Logging.cpp.i

SimpleHTTPServer/tool/Logging.s: SimpleHTTPServer/tool/Logging.cpp.s

.PHONY : SimpleHTTPServer/tool/Logging.s

# target to generate assembly for a file
SimpleHTTPServer/tool/Logging.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/Logging.cpp.s
.PHONY : SimpleHTTPServer/tool/Logging.cpp.s

SimpleHTTPServer/tool/epollHelp.o: SimpleHTTPServer/tool/epollHelp.cpp.o

.PHONY : SimpleHTTPServer/tool/epollHelp.o

# target to build an object file
SimpleHTTPServer/tool/epollHelp.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/epollHelp.cpp.o
.PHONY : SimpleHTTPServer/tool/epollHelp.cpp.o

SimpleHTTPServer/tool/epollHelp.i: SimpleHTTPServer/tool/epollHelp.cpp.i

.PHONY : SimpleHTTPServer/tool/epollHelp.i

# target to preprocess a source file
SimpleHTTPServer/tool/epollHelp.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/epollHelp.cpp.i
.PHONY : SimpleHTTPServer/tool/epollHelp.cpp.i

SimpleHTTPServer/tool/epollHelp.s: SimpleHTTPServer/tool/epollHelp.cpp.s

.PHONY : SimpleHTTPServer/tool/epollHelp.s

# target to generate assembly for a file
SimpleHTTPServer/tool/epollHelp.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/epollHelp.cpp.s
.PHONY : SimpleHTTPServer/tool/epollHelp.cpp.s

SimpleHTTPServer/tool/errHelp.o: SimpleHTTPServer/tool/errHelp.cpp.o

.PHONY : SimpleHTTPServer/tool/errHelp.o

# target to build an object file
SimpleHTTPServer/tool/errHelp.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/errHelp.cpp.o
.PHONY : SimpleHTTPServer/tool/errHelp.cpp.o

SimpleHTTPServer/tool/errHelp.i: SimpleHTTPServer/tool/errHelp.cpp.i

.PHONY : SimpleHTTPServer/tool/errHelp.i

# target to preprocess a source file
SimpleHTTPServer/tool/errHelp.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/errHelp.cpp.i
.PHONY : SimpleHTTPServer/tool/errHelp.cpp.i

SimpleHTTPServer/tool/errHelp.s: SimpleHTTPServer/tool/errHelp.cpp.s

.PHONY : SimpleHTTPServer/tool/errHelp.s

# target to generate assembly for a file
SimpleHTTPServer/tool/errHelp.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/errHelp.cpp.s
.PHONY : SimpleHTTPServer/tool/errHelp.cpp.s

SimpleHTTPServer/tool/io.o: SimpleHTTPServer/tool/io.cpp.o

.PHONY : SimpleHTTPServer/tool/io.o

# target to build an object file
SimpleHTTPServer/tool/io.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/io.cpp.o
.PHONY : SimpleHTTPServer/tool/io.cpp.o

SimpleHTTPServer/tool/io.i: SimpleHTTPServer/tool/io.cpp.i

.PHONY : SimpleHTTPServer/tool/io.i

# target to preprocess a source file
SimpleHTTPServer/tool/io.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/io.cpp.i
.PHONY : SimpleHTTPServer/tool/io.cpp.i

SimpleHTTPServer/tool/io.s: SimpleHTTPServer/tool/io.cpp.s

.PHONY : SimpleHTTPServer/tool/io.s

# target to generate assembly for a file
SimpleHTTPServer/tool/io.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/io.cpp.s
.PHONY : SimpleHTTPServer/tool/io.cpp.s

SimpleHTTPServer/tool/nethelp.o: SimpleHTTPServer/tool/nethelp.cpp.o

.PHONY : SimpleHTTPServer/tool/nethelp.o

# target to build an object file
SimpleHTTPServer/tool/nethelp.cpp.o:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/nethelp.cpp.o
.PHONY : SimpleHTTPServer/tool/nethelp.cpp.o

SimpleHTTPServer/tool/nethelp.i: SimpleHTTPServer/tool/nethelp.cpp.i

.PHONY : SimpleHTTPServer/tool/nethelp.i

# target to preprocess a source file
SimpleHTTPServer/tool/nethelp.cpp.i:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/nethelp.cpp.i
.PHONY : SimpleHTTPServer/tool/nethelp.cpp.i

SimpleHTTPServer/tool/nethelp.s: SimpleHTTPServer/tool/nethelp.cpp.s

.PHONY : SimpleHTTPServer/tool/nethelp.s

# target to generate assembly for a file
SimpleHTTPServer/tool/nethelp.cpp.s:
	$(MAKE) -f CMakeFiles/httpServer.dir/build.make CMakeFiles/httpServer.dir/SimpleHTTPServer/tool/nethelp.cpp.s
.PHONY : SimpleHTTPServer/tool/nethelp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... httpServer"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... SimpleHTTPServer/base/CurrentThread.o"
	@echo "... SimpleHTTPServer/base/CurrentThread.i"
	@echo "... SimpleHTTPServer/base/CurrentThread.s"
	@echo "... SimpleHTTPServer/base/GlobalConfig.o"
	@echo "... SimpleHTTPServer/base/GlobalConfig.i"
	@echo "... SimpleHTTPServer/base/GlobalConfig.s"
	@echo "... SimpleHTTPServer/base/HTTPTask.o"
	@echo "... SimpleHTTPServer/base/HTTPTask.i"
	@echo "... SimpleHTTPServer/base/HTTPTask.s"
	@echo "... SimpleHTTPServer/base/ListenServer.o"
	@echo "... SimpleHTTPServer/base/ListenServer.i"
	@echo "... SimpleHTTPServer/base/ListenServer.s"
	@echo "... SimpleHTTPServer/base/main.o"
	@echo "... SimpleHTTPServer/base/main.i"
	@echo "... SimpleHTTPServer/base/main.s"
	@echo "... SimpleHTTPServer/tool/Buffer.o"
	@echo "... SimpleHTTPServer/tool/Buffer.i"
	@echo "... SimpleHTTPServer/tool/Buffer.s"
	@echo "... SimpleHTTPServer/tool/Cache.o"
	@echo "... SimpleHTTPServer/tool/Cache.i"
	@echo "... SimpleHTTPServer/tool/Cache.s"
	@echo "... SimpleHTTPServer/tool/HTTP/httpContext.o"
	@echo "... SimpleHTTPServer/tool/HTTP/httpContext.i"
	@echo "... SimpleHTTPServer/tool/HTTP/httpContext.s"
	@echo "... SimpleHTTPServer/tool/LogStream.o"
	@echo "... SimpleHTTPServer/tool/LogStream.i"
	@echo "... SimpleHTTPServer/tool/LogStream.s"
	@echo "... SimpleHTTPServer/tool/Logger.o"
	@echo "... SimpleHTTPServer/tool/Logger.i"
	@echo "... SimpleHTTPServer/tool/Logger.s"
	@echo "... SimpleHTTPServer/tool/Logging.o"
	@echo "... SimpleHTTPServer/tool/Logging.i"
	@echo "... SimpleHTTPServer/tool/Logging.s"
	@echo "... SimpleHTTPServer/tool/epollHelp.o"
	@echo "... SimpleHTTPServer/tool/epollHelp.i"
	@echo "... SimpleHTTPServer/tool/epollHelp.s"
	@echo "... SimpleHTTPServer/tool/errHelp.o"
	@echo "... SimpleHTTPServer/tool/errHelp.i"
	@echo "... SimpleHTTPServer/tool/errHelp.s"
	@echo "... SimpleHTTPServer/tool/io.o"
	@echo "... SimpleHTTPServer/tool/io.i"
	@echo "... SimpleHTTPServer/tool/io.s"
	@echo "... SimpleHTTPServer/tool/nethelp.o"
	@echo "... SimpleHTTPServer/tool/nethelp.i"
	@echo "... SimpleHTTPServer/tool/nethelp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

